name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main  # Change to your default branch if different

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 (Zulu)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.xml', '**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install dependencies
      run: mvn install

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set SONAR_TOKEN as an environment variable

    - name: Upload Quality Gate status
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set SONAR_TOKEN as an environment variable
