name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 (Zulu)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.xml', '**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install dependencies
      run: mvn install

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        # You can also specify properties here as needed
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        organization: ${{ secrets.SONAR_ORG }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure the token is set
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # Set your project key
        SONAR_ORG: ${{ secrets.SONAR_ORG }}  # Set your organization key

    - name: Upload Quality Gate status
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        # Same for the upload step
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        organization: ${{ secrets.SONAR_ORG }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_ORG: ${{ secrets.SONAR_ORG }}
